"""PPPoE access concentrator — monthly subscriber accounts.

Recurring-revenue accounts (username/password + a plan expiry) that dial in over
PPPoE, separate from the coin/voucher hotspot. This module renders the DB
accounts into /etc/ppp/chap-secrets (which pppoe-server reads live per auth) and
expires overdue plans. The pppoe-server service + options/pool are set up by
install.sh (only when `pppoe_enabled`). No-ops off-Linux (dev/mock).
"""
import os
import subprocess
import sys

MOCK = not sys.platform.startswith("linux")
CHAP = "/etc/ppp/chap-secrets"


def write_chap_secrets(accounts):
    """Rewrite chap-secrets from the account list; only enabled accounts can auth."""
    if MOCK:
        return
    lines = ["# generated by PisoWiFi — edit accounts in the admin UI\n"]
    for a in accounts:
        if a.get("enabled"):
            lines.append('"%s"\t*\t"%s"\t*\n' % (a["user"], a["password"]))
    try:
        with open(CHAP, "w") as f:
            f.writelines(lines)
        os.chmod(CHAP, 0o600)
    except Exception:
        pass


def enforce(db):
    """Expire overdue plans, then sync chap-secrets. Returns #expired.
    Cheap enough to call from the reconcile loop."""
    n = db.expire_pppoe_accounts() if not MOCK else 0
    write_chap_secrets(db.list_pppoe_accounts())
    return n


def service(action):
    if MOCK:
        return
    subprocess.run(["systemctl", action, "pppoe-server"], capture_output=True)
