"""Tethering detection.

## Why the first attempt cut customers off the internet

v1 dropped any client packet whose TTL was not an OS initial value (64, 128,
255), on the reasoning that a hotspot decrements TTL when it forwards, so a
lower TTL means a shared device. The arithmetic is right and the conclusion is
wrong, because a phone decrements its own traffic too whenever an on-device VPN
is running -- ad blockers, Private DNS, WARP, corporate VPN clients all take
packets into a local tun and re-inject them, and the phone's own stack forwards
them on the way through. Every packet that customer sends is then one lower,
forever, and v1 dropped all of it. They could not browse at all.

The evidence that misled us is worth keeping: on the test phone, ICMP echo
replies came back at TTL 64 while its TCP traffic left at 63. That looked like
"the phone at 64, something behind it at 63". It is equally consistent with a
local VPN, because echo replies are generated by the kernel directly and never
pass through the tun.

## What actually identifies tethering

Not a low TTL -- *two different TTLs from one MAC at the same time*.

    phone alone                 -> 64 only        (ttl_norm)
    phone with a local VPN      -> 63 only        (ttl_fwd)      NOT tethering
    phone sharing to a laptop   -> 64 AND 63      (both sets)    tethering

A device only ever originates at one initial TTL. Two populations from a single
MAC means one of them was forwarded, and the forwarder is the device itself.

nftables records the MACs into `ttl_norm` and `ttl_fwd` without dropping
anything; this module intersects them. Enforcement is opt-in, per device, and
applies only to MACs confirmed here.
"""
import re
import subprocess

TABLE = "inet pisowifi"
NORM, FWD, BLOCK = "ttl_norm", "ttl_fwd", "tether_block"

_MAC = re.compile(r"\b([0-9a-f]{2}(?::[0-9a-f]{2}){5})\b", re.I)


def _nft(*args):
    try:
        return subprocess.run(("nft",) + args, capture_output=True, text=True,
                              timeout=5)
    except (OSError, subprocess.SubprocessError):
        return subprocess.CompletedProcess(args, 1, "", "nft unavailable")


def _members(set_name):
    """MACs currently in an nft set. Empty on any failure -- this is
    diagnostics, and it must never be the reason the portal stops working."""
    r = _nft("list", "set", *TABLE.split(), set_name)
    if r.returncode != 0:
        return set()
    body = r.stdout.split("elements = {", 1)
    if len(body) < 2:
        return set()
    return {m.group(1).lower() for m in _MAC.finditer(body[1])}


def observe():
    """Current picture, per MAC.

    Returns {mac: {"own": bool, "forwarded": bool, "tethering": bool}}.
    `tethering` is the intersection and nothing else.
    """
    norm, fwd = _members(NORM), _members(FWD)
    out = {}
    for mac in norm | fwd:
        own, forwarded = mac in norm, mac in fwd
        out[mac] = {
            "own": own,
            "forwarded": forwarded,
            "tethering": own and forwarded,
        }
    return out


def tethering_macs():
    return {mac for mac, s in observe().items() if s["tethering"]}


def blocked_macs():
    return _members(BLOCK)


def enforce(macs):
    """Add confirmed tethering MACs to the enforcement set.

    Adding is idempotent and refreshes the timeout, so a device that stops
    tethering ages out on its own rather than needing to be removed. Returns
    the MACs actually pushed.
    """
    done = set()
    for mac in macs:
        if not _MAC.fullmatch(mac):
            continue                       # never interpolate unvalidated text
        r = _nft("add", "element", *TABLE.split(), BLOCK, "{ %s }" % mac)
        if r.returncode == 0:
            done.add(mac.lower())
    return done


def release(mac):
    """Stop enforcing against one device, for an owner overruling a detection."""
    if not _MAC.fullmatch(mac or ""):
        return False
    return _nft("delete", "element", *TABLE.split(), BLOCK,
                "{ %s }" % mac).returncode == 0


def summary(enforcing):
    """Snapshot for the dashboard."""
    seen = observe()
    tethering = sorted(m for m, s in seen.items() if s["tethering"])
    vpn_like = sorted(m for m, s in seen.items()
                      if s["forwarded"] and not s["own"])
    return {
        "enabled": bool(seen) or True,
        "enforcing": bool(enforcing),
        "watched": len(seen),
        "tethering": tethering,
        "blocked": sorted(blocked_macs()),
        # Surfaced deliberately. These are the devices v1 cut off, and showing
        # them is what makes "we are not blocking these" auditable rather than
        # a claim in a comment.
        "vpn_like": vpn_like,
    }
